### ISSUE TITLE
Normalizing components

### ISSUE THREAD

**Issue by yanickrochon** [sricho/react-flexboxgrid#11]
I'd be happy to contribute to this project, however you are missing many options from flexboxgrid, and your components are not normalized.

Typically, all grid systems use this format

```
<Grid>
  <Row>
    <Col />
  </Row>
</Grid>
```

Where a `Grid` has a `container` class and may be `fluid`. Etc.

Would you be ok if I submit a PR to fix this? I can simply add the missing components, leaving the existing ones there and mark them as deprecated at best. The point is to allow supporting all the features of flexboxgrid, and am I not happy with how [react-flexbox-grid](https://github.com/roylee0704/react-flexbox-grid) depends on Webpack. There is really no need for yet another wrapper...

**Comment by sricho** [comment]
Hi @yanickrochon,

I agree 100% with everything that you said. A PR would be great! There may also need to be a few dependency updates as I haven't touched this project for a while. I'll get to that in a couple of days.

**Comment by yanickrochon** [comment]
Already [working on this](https://github.com/yanickrochon/react-flexboxgrid/tree/normalization). Tell me what you think. I got to go home, but I'll try to finish up tonight.

**Comment by yanickrochon** [comment]
Right. So I made a lot of changes, and updated all deps, and added / removed some, etc.

In that branch, I also removed `GridColumn` and `GridRow`, and I could restore them if you insist, but since this module is fairly unknown, I don't think there are too many projects relying on these.

There is one test, and it passes.

**Comment by sricho** [comment]
Great. Yeah that makes sense to remove those. We can bump it to a major version to indicate breaking changes in the version number so no need to keep them around.

Excellent job on the test. Once it is merged in to master I can complete the rest of the tests and have it run on Travis.

**Comment by yanickrochon** [comment]
I was trying to make it work with Meteor, but unsuccessfully. I'll finish up one or two things and will make a PR.
