### ISSUE TITLE
Needs react 0.14 allowed as a peer dep

### ISSUE THREAD

**Issue by lparry** [sricho/react-flexboxgrid#4]
Come on stu!

**Comment by roylee0704** [comment]
+1

**Comment by roylee0704** [comment]
meanwhile you might want to check this out. @Iparry

https://github.com/roylee0704/react-flexbox-grid

**Comment by frankf-cgn** [comment]
@sricho Can I do anything to support you accepting the PRs?

**Edit:** Oh, sorry man, just see this is already done in your codebase.
@roylee0704: Think you can close this issue

**Comment by sricho** [comment]
Sorry guys. I didn't have my notifications set up properly and realise that people were using this! I updated the dependencies and pushed a new minor version last week to `0.3.0`. I'll close this issue.

@frankf-cgn Thank you for the offer but I should be good now I realise that people are using this. Doh.
