### ISSUE TITLE
Allow GridRow and GridColumn to be styleable

### ISSUE THREAD

**Issue by frankf-cgn** [sricho/react-flexboxgrid#5]
I need to set a min-height of a `<GridRow>` and I it would be nice beeing able to do that without to fallback on "divities".
See my PR for a possible implementation.

**Comment by sricho** [comment]
Good idea. I want to head in the direction of having specific alignment props passed in for vertical spacing. Passing through the `styles` for the moment is a good start until that is done. Thanks @frankf-cgn
